version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
    ports:
      - '5432:5432'
    networks:
      - network
    volumes:
      - pg_data:/var/lib/postgresql/data

  bookshelf:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bookshelf?schema=public
    ports:
      - '3000:3000'
    networks:
      - network
    depends_on:
      - postgres

networks:
  network:
    driver: bridge

volumes:
  pg_data:
    driver: local
